### ISSUE TITLE
Bug: Lots of types missing from latest version

### ISSUE THREAD

**Issue by prescience-data** [fullstack-build/tslog#165]
**Describe the bug**
Our application linting rules require explicit typing of objects as they are defined, so we use(d) the provided interfaces from the  `tslog` package.

Example:
```typescript
import type { ILogObject, ISettings, ILogObject, TLogLevelName, TTransportLogger, Logger } from "tslog"
```

**To Reproduce**

1. Attempt to import any types previously exposed.
2. Most imports now fail.

**Expected behavior**
This breaking change may have possibly been intentional, so apologies in advance if so. 

However, this forces us to manually define all the types we use from the application, which creates a lot of room for potential decoupling from internal types as they are changed. Whereas with tight 1:1 binding, we can be sure objects defined locally always match the interface intended by `tslog`. 

An example of this might be a property defined as a raw `string` today,  but over time `tslog` adds nicer `"foo" | "bar" | string` types which do not break the interface locally, but we miss out on the newer narrower types as local interface will still be merely `string`. 

Would be awesome if most (if not all) types that may be required outside the `tslog` instance (especially during setup) could be exposed publicly. 🙏

**Comment by kevintechie** [comment]
In the latest version, not all those types exist. The API has changed, and you will need to update your code.

**Comment by terehov** [comment]
Thank you for your issue. 
tslog follows semantic versioning. A major version change means a breaking API change. 
In fact V4 is a complete rewrite, works now on the server and in browsers and is way more flexible. 
You can now define your own log methods as well as the log object itself. That’s why this interface is not exposed anymore, since you can define it yourself, as explained here: 

https://tslog.js.org/#/?id=defining-and-accessing-logobj
