### ISSUE TITLE
Feature Request: Mutating logger settings (v4)

### ISSUE THREAD

**Issue by beanaroo** [fullstack-build/tslog#176]
**Description / Use Case for a Feature**

In v3, the implementation had a method `setSettings` which enabled modifying minLevel and output configuration at runtime.

In v4, is this no longer possible or is there an alternative approach recommended?

I tried extending the Logger but `settings` is private and only accessible within the `BaseLogger ` class.

**Comment by kevintechie** [comment]
I was able to get around this by using `getSubLogger({ minLevel: 2 })` for setting minLevel at runtime, but this is not ideal as it results in a logger name of `parent:child` when I don't really need a child logger.

In v3 and with other loggers, I had been creating a logger as soon as the app started and then loading the configuration options from a config file and updating the logger config. In v4 this wasn't possible, so I just switched to `getSubLogger()`.

In the end, I re-wrote my code to instantiate the logger at the last moment when I know the final state of the configuration options. This works for me because I don't need to change `minLevel` dynamically as a result of user input or other runtime logic.

**Comment by terehov** [comment]
I wish you told me about that earlier. I didn't see this use case and was trying to remove as much junk as possible. I figured: When people need it, they will tell me. Which you did. 
I am working on a new release now and will probably just set settings to public, when I don't find any edge cases.

**Comment by terehov** [comment]
Added in `V4.3.0`. Just released.
