### ISSUE TITLE
Feature Request: Add fileNameWithLine variable to log message formats

### ISSUE THREAD

**Issue by darklow** [fullstack-build/tslog#182]
**Description / Use Case for a Feature**

Would it be possible to add `fileNameWithLine` variable to log message format especially for `prettyLogTemplate`. My current paths depths are quite long and therefore the message itself is shifted way far from the beginning of a message and makes hard to read. In browser there is even hostname, which makes these paths very very long before you read actual message.

Another, more flexible way how this could be solved by some sort of optional callback where each var could be intercepted and every user could adjust every param according to their needs, where I would for example keep just last_directory/fileName:line, but some other user might have different preference. This would eliminate similar requests in the future.

But if this sounds too complicated, then adding `fileNameWithLine` would be good and short enough and by filename and line you can pretty much find the right place which caused the log.

Thanks.

**Comment by terehov** [comment]
Thank you. I see where you're coming from. I will put in some thoughts and add something in the upcoming version. Callback sounds like an elegant solution.

**Comment by terehov** [comment]
@darklow I have decided to add `fileNameWithLine` for now. 
The hostname is in there in order to make it clickable in the console. With source maps, it's super convenient to be able to jump right to the source position.  
I do agree that callbacks would be a flexible option, however also not the most performant one. Therefore, I decided not to introduce them just yet.

**Comment by terehov** [comment]
V4.6.0 adds `fileNameWithLine `.
