### ISSUE TITLE
Feature Request: Full `IMeta` compatibility for `getMeta` return-type.

### ISSUE THREAD

**Issue by prescience-data** [fullstack-build/tslog#201]
**Description / Use Case for a Feature**

https://github.com/fullstack-build/tslog/blob/5e21e7392a0426c22c99fa7a039e7a029b890c9c/src/runtime/nodejs/index.ts#L44-L45

Filed as a `Feature Request` rather than a `Bug` as this may be intentional - but I note that the existing code has the ability to set the `path` property as `undefined` breaks the `IMeta` contract, forcing an `as IMeta` assertion, which may make debugging nasty in the future. 

Would it be practical to either:
a) update the `IMeta` contract to make the `path` property as optional, or;
b) use an empty object `{}` instead of `undefined` on line 44 which would fulfil the `IMeta` contract?

The only caveat with `b`: I don't imagine there are any `undefined` checks elsewhere in the code base, given the `IMeta` interface does not expect to ever see `undefined` here, but if so this would require a `{}` equality check rather than `undefined`.

**Comment by terehov** [comment]
Thank you for pointing it out. And I can see why you considered labelling it as a bug. 
With the last performance release, this field became optional, however, I forgot to update the interface accordingly. 

I would prefer to go with `a`since I am not a fan of an "empty object". If something isn't there (due to a configuration or whatsoever) it should explicitly NOT BE THERE in the form of an `undefined`or a `null`. 
Therefore, I am going to update the interface accordingly. 
In the code, you can find that it's already optional here:
https://github.com/fullstack-build/tslog/blob/master/src/BaseLogger.ts#L327

**Comment by terehov** [comment]
`V4.7.1` makes it optional in the interface.
