### ISSUE TITLE
Not a bug: Color pallet

### ISSUE THREAD

**Issue by minmur** [fullstack-build/tslog#22]
It's not a bug but some recommendations are needed. I'm using iTerm + Oh-My-Zsh with Powerlevel10k and can't get those nice colors you have in the screenshot any how.

Can you recommend what was used to get shiny and beautiful looking logs?

Here is what i see:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/942831/85095946-943aa380-b1fb-11ea-8f46-d193f35a5335.png">

**Comment by terehov** [comment]
Hi, @minmur thanks for reaching out. 
In order to avoid unnecessary dependencies like `chalk` and further improve our performance, `tslog` only uses the native colors available through Node.js `util`. Older versions <12 don't support the entire palette and fall-back to black and white. 

I guess you are still running on an older version and would suggest updating to the current LTS (12.x) version. 
Does it solve your issue? If it doesn't, I would kindly ask you to provide me with your Node.js and OS versions and re-open this issue. Thanks
 
cheers

Eugene

**Comment by minmur** [comment]
My OS is macOS Catalina. Node version 12.5.0 (via nvm)

I have cleared all my terminal setting and installed everything again. And it the same.

**Comment by terehov** [comment]
Thanks. I'll have a look at it.

**Comment by terehov** [comment]
@minmur I checked it out and "Oh-My-Zsh" seems to be ignoring or overwriting our styles.  

**Both on iTerm:**

Without "Oh-My-Zsh":
![image](https://user-images.githubusercontent.com/490885/85221309-2df88100-b3b3-11ea-9337-15ab77b3d269.png)

With "Oh-My-Zsh": 
![image](https://user-images.githubusercontent.com/490885/85221313-3cdf3380-b3b3-11ea-9f01-0621bd99c9b1.png)

If you have some time, it would be amazing if you could have a look and try to fix it! 

Thanks!

**Comment by herbertpan** [comment]
Hi @terehov 
do you have a plan to support metaline color customization?

If I find the correct [place](https://github.com/fullstack-build/tslog/blob/master/src/LoggerWithoutCallSite.ts#L617), the metaline color is hard coded as gray.
```
if (concatenatedMetaLine.length > 0) {
      std.write(
        LoggerHelper.styleString(
          ["gray"],
          `[${concatenatedMetaLine}]`,
          this.settings.colorizePrettyLogs
        )
      );
```
My iterm2 background is gray, so I cannot see metaline. (I have to use `colorizePrettyLogs: false`)

**Comment by terehov** [comment]
@herbertpan Makes sense. Thank you. 
I am going to add it to the V4 release too.

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you.
